apiVersion: v1
kind: Secret
metadata:
  name: fastapi-server-credentials
  namespace: default
stringData:
  .env: |
    SECRET_KEY=cd2f9f6e68b393db456c90f15a5a7faded32bee62abbefe068f9fca0bc4e3b85
    DATABASE_URL=postgresql://postgres:postgres@postgres-db-service:5432/tododb